# Generated by Django 2.2.7 on 2019-12-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='投票标题')),
                ('description', models.CharField(max_length=255, verbose_name='选项描述')),
                ('up', models.IntegerField(verbose_name='同意票数')),
                ('down', models.IntegerField(verbose_name='反对票数')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('skey', models.TextField(verbose_name='私钥')),
                ('pkey', models.TextField(verbose_name='公钥')),
                ('q', models.TextField(verbose_name='大素数')),
                ('n', models.TextField(verbose_name='素数')),
                ('g', models.TextField(verbose_name='基点')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votemes', models.TextField(verbose_name='盖章信息')),
            ],
        ),
    ]
