# Generated by Django 2.2.7 on 2019-12-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='down',
            field=models.CharField(max_length=255, verbose_name='反对票数'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='up',
            field=models.CharField(max_length=255, verbose_name='同意票数'),
        ),
    ]
