# Generated by Django 2.2.7 on 2019-12-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20191226_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='votemes',
            field=models.TextField(unique=True, verbose_name='盖章信息'),
        ),
    ]
